version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, "type:chore"]
    commit-message:
      prefix: "chore(deps)"
    groups:
      python-minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directory: /rust/nhs_stats_core
    schedule:
      interval: weekly
    labels: [dependencies, "type:chore"]
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: monthly
    labels: [dependencies, "type:chore"]
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, "type:chore"]
    commit-message:
      prefix: "chore(ci)"
